### ISSUE TITLE
Cannot build combatlog from the project root 

### ISSUE THREAD

**Issue by luclacdaudinh** [skadistats/clarity-examples#12]
After building it from the project root with
mvn -P combatlog package

Here is what I got from cmd:
[ERROR] /C:/clarity-examples-c824a92334456a7f462b177dabe176a02e7981d6/src/main/java/skadistats/clarity/examples/combatlog/Main.java:[8,32] cannot find symbol
[ERROR] symbol:   class CombatLogEntry
[ERROR] location: package skadistats.clarity.model
[ERROR] /C:/clarity-examples-c824a92334456a7f462b177dabe176a02e7981d6/src/main/java/skadistats/clarity/examples/combatlog/Main.java:[31,44] cannot find symbol
[ERROR] symbol:   class CombatLogEntry
[ERROR] location: class skadistats.clarity.examples.combatlog.Main

**Comment by spheenik** [comment]
There were some big updates today regarding combat log, make sure you 
have the newest version of clarity (today's 2.1-SNAPSHOT).
It has that file:

https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/model/CombatLogEntry.java

|mvn -U |-P combatlog package

should do the trick :)

**Comment by luclacdaudinh** [comment]
Works like a charm!! Thank you so much!

**Comment by spheenik** [comment]
You're welcome!
