### ISSUE TITLE
Hero net worth

### ISSUE THREAD

**Issue by nekklo** [skadistats/clarity-examples#13]
Hi again, 

I would like to start by thanking you for all the help in the previous issues I had. I got a new question that I would need some help on. Is the net worth value stored somewhere as a variable? I can get the gold earned, reliable gold, unreliable gold etc but I'm missing the net worth.

Thank you again.

**Comment by spheenik** [comment]
Sorry for not replying earlier.
I don't think networth is stored. You'd have to determine the items and their worth in the inventory, and add that to the reliable and unreliable gold.

**Comment by nekklo** [comment]
Hi spheenik,

Thanks for you reply. That's what I thought also :/

**Comment by bwarren2** [comment]
On the CDOTA_DataRadiant Entity you can find these attributes, which might be useful:

CDOTA_DataRadiant

| FP       | Property                                                     | Value                                    |
|---|---|---|
| 0      | m_iTeamNum                                    | 2                    |
| 1      | m_vecDataTeam                                 | 5                    |
| 1/0/0  | m_vecDataTeam.0000.m_iTotalEarnedGold         | 8527                 |
| 1/0/1  | m_vecDataTeam.0000.m_iReliableGold            | 92                   |
| 1/0/2  | m_vecDataTeam.0000.m_iUnreliableGold          | 610                  |
| 1/0/3  | m_vecDataTeam.0000.m_iStartingPosition        | -1                   |
| 1/0/4  | m_vecDataTeam.0000.m_iTotalEarnedXP           | 8404                 |
| 1/0/5  | m_vecDataTeam.0000.m_iSharedGold              | 554                  |
| 1/0/6  | m_vecDataTeam.0000.m_iHeroKillGold            | 1326                 |
| 1/0/7  | m_vecDataTeam.0000.m_iCreepKillGold           | 2531                 |
| 1/0/8  | m_vecDataTeam.0000.m_iIncomeGold              | 

Use the same lookup formatting as in the matchend example to access them.

**Comment by nekklo** [comment]
Hi Warren,

Thanks for your reply. Will check it out.
