### ISSUE TITLE
How to get position in combat log

### ISSUE THREAD

**Issue by cqiaoben** [skadistats/clarity-examples#16]
For example if Hero A killed unit B, how to get position of A and B?

**Comment by spheenik** [comment]
Code for getting position:

https://gist.github.com/spheenik/3766744d47c170f25cf5

The code is from Source 1, the property m_cellbits is not existing anymore in Source 2, and can be replaced by the constant value 7.

**Comment by spheenik** [comment]
...and there is no more Vector2f in current clarity, there is now m_cell[XYZ] and m_vec[XYZ]

**Comment by cqiaoben** [comment]
Thanks for the reply! Sorry I didn't make my question clear. I am more interested in getting the unit B or hero A as an entity, so that I could retrieve its location. I know getAttackerNameCompiled(cle) could get the name of the attacker, but it's not a Dtname.

**Comment by spheenik** [comment]
There is no direct correlation from combat log to entity in the replay unfortunately.
