### ISSUE TITLE
Problems with replays generated by the 'record' console command

### ISSUE THREAD

**Issue by noggan** [skadistats/clarity-examples#17]
I'm having issues parsing replays that is generated by the `record` console command which I thought would be supported with the 2.1-SNAPSHOT. Running regular replays works fine.

When running `combatlog` it finishes but no data is presented.

When running `matchend` I get the following exceptions:
http://caps.interactivesolutions.se/ss/3a74bf.png.

Is there something I need to keep in mind when creating a replay from the console in order for this to work?

**Comment by spheenik** [comment]
It worked a while ago (think 6 months).
I did a quick test right now, and I can reproduce your problem. 
I will do some analysis on what has changed soonish.

**Comment by spheenik** [comment]
Fixed the exception with the matchend example with https://github.com/skadistats/clarity/commit/0400ceddbfbebd97ff0f77a578ba7d674329c0ab. Pushed a new snapshot, so you can test that right now.

Checking the combat log messages now.

**Comment by spheenik** [comment]
Ok, combat log messages are missing when you do a bot game. They simply are not in the file.
When you spectate a match and record there, you will have combat log.
Must be a bug on Valve's side.

**Comment by spheenik** [comment]
Pushed another snapshot which fixes some issues with the combat log in console recorded replays. 
Console recorded replays now work on my side. Please check, and close the bug if appropriate. Thank you :)

**Comment by noggan** [comment]
Thanks for the quick fixes. I tried spectating a public game now and recorded a piece of the game using `record`. The combat log command is working fine now. However I'm still receiving the exact same error when running the `matchend` command.

**Comment by noggan** [comment]
I just tried spectating some friends facing each other in a 1v1 and recorded the match through the console. The combat log works fine but I received a new exception when running the `matchend` command: http://caps.interactivesolutions.se/ss/5898d1.png. Any ideas?

**Comment by spheenik** [comment]
The matchend example probably 10 players, and falls over less of them being available.
Can you send the replay to clarity@martin.schrodt.org?
I can have a look at fixing the matchend example then...

**Comment by spheenik** [comment]
should be fixed with https://github.com/skadistats/clarity-examples/commit/f02fb116419fcd7a14106f45eb8e0fadfa0eba37

I did rewrite the whole thing though, so there might still be some bugs hiding...

**Comment by noggan** [comment]
Works for me now. I'll reopen if I find a bug.

Thanks for the help, much appreciated.
