### ISSUE TITLE
Can't run example (missing main class error)

### ISSUE THREAD

**Issue by GreenIreland** [skadistats/clarity-examples#18]
Hello! Explain me please what i am doing wrong. I am not java developer (.net) but i want to use your perfect framework parse system. So I stucked at beginning stage after build.

Tech info:
Apache Maven 3.3.9
Java version: 1.8.0_71, vendor: Oracle Corporation
OS name: "windows 8.1", version: "6.3", arch: "x86", family: "dos"

Got example pom file from : https://github.com/skadistats/clarity-examples/blob/master/pom.xml
Ofc didn't modified that.

Run build output
![image](https://cloud.githubusercontent.com/assets/16797529/12474929/1064bea4-c030-11e5-964e-86a09b0fe543.png)

Run jar output 
![image](https://cloud.githubusercontent.com/assets/16797529/12474934/1dac2534-c030-11e5-8bde-6c99f438849c.png)

I got 2 folders in "target": classes and test-classes. Both are empty.

Just in case... repository folder content is
![image](https://cloud.githubusercontent.com/assets/16797529/12474995/8c8bdbb6-c030-11e5-9933-e734de9e0695.png)

Please, help me, what steps i missed ?

**Comment by spheenik** [comment]
you got to choose the profile you want to build, for example

mvn -P combatlog package

**Comment by GreenIreland** [comment]
I tried this too. No difference unfortunately.
Seems, this doesn't work on other profiles too

run dumpbaselines
![image](https://cloud.githubusercontent.com/assets/16797529/12475227/846140d2-c032-11e5-9fc1-11948e28c764.png)

**Comment by spheenik** [comment]
It says "no sources to compile" in your screenshot.
It does not suffice to only get the pom.xml. You need to clone the whole project.

To clone: https://github.com/skadistats/clarity-examples.git

or if you prefer, just download and extract https://github.com/skadistats/clarity-examples/archive/master.zip

**Comment by GreenIreland** [comment]
Thank you! it works now! 
Can you advice how to configure slf4j.Logger to write file? And .. so, u can close this issue, ty very much

**Comment by spheenik** [comment]
To change the logging, configure `src/main/resources/logback.xml` to use a FileAppender. [Here is the documentation](http://logback.qos.ch/manual/appenders.html#FileAppender).

Good luck!
