### ISSUE TITLE
Missing Main Class in Examples

### ISSUE THREAD

**Issue by rahat5810** [skadistats/clarity-examples#2]
Hi,
I am new in Java programming, so I might be doing something wrong here. I want to extract the combat log. I used the "mvn -P combatlog package" command and then "java -jar target/combatlog.jar replay.dem" to parse the combat log. But it says Error: Could not find or load main class skadistats.clarity.examples.combatlog.Main. I extracted the combatlog.jar file and it does not have the example folder. Can you tell me what I am doing wrong?

**Comment by spheenik** [comment]
I hope it worked out, man :)
