### ISSUE TITLE
Two different class names used in different replays

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity-examples#21]
I noticed after downloading a replay from gosugamers that their replays all had classes that begin with DT_DOTA instead of CDOTA. Also, the replays that used DT_DOTA only had 2048 indexes for entities, whereas replays with CDOTA had 16384 so it seems that either some information is missing in DT_DOTA games or most of the classes are combined. They seem to be very different, I'm just not sure why. Any ideas?

**Comment by spheenik** [comment]
It's a Source 1 replay (pre Dota 2 Reborn).

**Comment by TodorovicF** [comment]
I see, thanks a lot for clearing that up!
