### ISSUE TITLE
How to get buff/debuff information

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity-examples#23]
I'm looking through the clarity analyzer and I can't seem to find the correct property within CDOTA_Unit_Hero_[heroname] to get the information of any buffs, such as Greevil's Greed or Arghanim's Scepter Synth. I've looked at other entities, but nothing looks like it has that information. Where is buff information stored for each character? Thanks a lot!

**Comment by spheenik** [comment]
This information is stored in the modifiers. There's some [basic code for dumping those](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/modifiers/Main.java).

**Comment by TodorovicF** [comment]
Thanks a lot! I've taken a look at it and I can't seem to find any information about the buff name in the modifier data. Is it given somewhere else?

**Comment by spheenik** [comment]
[There was a string table "ModifierNames" in Source 1](https://gist.github.com/spheenik/9179328).
Chances are it's still there.

**Comment by TodorovicF** [comment]
Thank you, that's exactly what I need!

**Comment by TodorovicF** [comment]
I forgot to add, for Rune use like Bounty rune, where there is not visible buff when the rune is used, how can I get the moment a rune is consumed, like when it shows up in the chat log?

**Comment by spheenik** [comment]
This is tough. You could listen for `@OnEntityDeleted` and check if it was a bounty rune.
If it was, you have to find the entity that took it. For that, you could use Overhead-events (special usermessage iirc, that get's emitted each time the little + gold animation gets played. Or you can check gold of heros, correlate with the heros position, and find the most probable one...

**Comment by TodorovicF** [comment]
Haha, I had a feeling it wasn't going to be simple. Thanks for the tips!
