### ISSUE TITLE
How to get Buyback/Respawn information

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity-examples#24]
Is there any way to get accurate buyback info, such as time left to respawn, gold lost from death, and gold cost to buyback? I've only noticed these properties within CDOTA_DataRadiant and CDOTA_DataDire:
m_vecDataTeam.000[x].m_fIBuybackCooldownTime
m_vecDataTeam.000[x].m_fIBuybackGoldLimitTime
m_vecDataTeam.000[x].m_fIBuybackCostTime

I'm not sure what the difference between these is or what BuybackCostTime and BuybackGoldLimitTime actually mean.

There are also the combatlog entries DOTA_COMBATLOG_BUYBACK and DOTA_COMBATLOG_DEATH, but I can't seem to extract gold lost from death or buyback.

I'm I looking in the wrong place? Thanks a lot!

**Comment by spheenik** [comment]
I've never worked with those vars, so I'll pass it to whoever comes around and knows :)
