### ISSUE TITLE
Getting unit Entities from CombatLog

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity-examples#25]
I'm using the CombatLog to get some information on targets and attackers, but the only unit information that seems available are the name and the team through getAttackerName/getTargetName, and getAttackerTeam/getTargetTeam. If, for instance, the target or attacker is a neutral/lane creep, is there any way I can get that specific unit's Entity? So if I get a "npc_dota_creep_badguys_ranged" from the CombatLog, how can I get its Entity so that I can extract other data like position? Thanks!

**Comment by spheenik** [comment]
Nope, there isn't.

**Comment by TodorovicF** [comment]
No worries, thanks so much for replying and for the awesome parser!

**Comment by spheenik** [comment]
You're welcome :)

**Comment by spheenik** [comment]
I gotta add, this would be a really useful addition from Valve.
