### ISSUE TITLE
About GameEvent

### ISSUE THREAD

**Issue by jihua0125** [skadistats/clarity-examples#27]
Hi,

I really appreciate your job and it is excellent. However, I am a noob to Java, so reading your code is kind of hard for me. My friends and I are interested in analyzing ward placements. SO I am wondering how can I get the wards information from your code. Thanks a lot!

**Comment by spheenik** [comment]
Have a look at yasp's implementation. It will push you in the right direction.

https://github.com/yasp-dota/yasp/blob/master/java_parser/src/main/java/yasp/Main.java

**Comment by jihua0125** [comment]
Thanks! I will have a look. I am really poor at Java, for I am more focus on Python and R. Anyway, thanks for your job!
