### ISSUE TITLE
Question: connect/disconnect logs

### ISSUE THREAD

**Issue by ThorConzales** [skadistats/clarity-examples#29]
Hi,

Could you point me to right direction here how to get player connection/reconnection and disconnection logs. If there is not a built in event for listening those maybe you happen to know protobuf message class name(s) that is handling those events?

**Comment by spheenik** [comment]
Hmm, I do not know exactly. I suspect it might be a certain GameEvent. 
I am almost sure there is no dedicated protobuf-message for this. 

You can get a list of all possible game events like this:

```java
public class DumpGameEvents {
   @OnGameEventDescriptor
    public void onGameEventDescriptor(Context ctx, GameEventDescriptor descriptor) {
        System.out.println(descriptor);
    }
    public static void main(String[] args) throws Exception {
        new SimpleRunner(new MappedFileSource(args[0])).runWith(new DumpGameEvents());
    }
}

**Comment by ThorConzales** [comment]
Thank, I'll try to filter through those event.

**Comment by spheenik** [comment]
Sure, and if you do not find it, reopen :)
