### ISSUE TITLE
How to dump the results into txt or json file?

### ISSUE THREAD

**Issue by zzd1992** [skadistats/clarity-examples#35]
What is the easiest way to dump the results into txt or json file?

By the way, here is an example:
"094220: CDOTA_Unit_Hero_WitchDoctor at index 264 has died"
What 'index 264' means?
And '094220' is the frame index the game, 30 frames per second. Am I right?

**Comment by spheenik** [comment]
A good place to start is the [OpenDota parser](https://github.com/odota/parser/blob/master/src/main/java/opendota/Parse.java), as well as [clarity's example code](https://github.com/skadistats/clarity-examples).

The index is the position of the entity in the entity table (nothing you should care about).

Your assumption about the frame number is correct, and it's 30 FPS.
