### ISSUE TITLE
Hi! What is the standard map size and coordinate boundary?

### ISSUE THREAD

**Issue by CharlesLiuyx** [skadistats/clarity-examples#37]
I notice that in the project clarity-analyzer
```
MIN_X = -7500
MAX_X = 7500
MIN_Y = -7400
MAX_Y = 7200
```
Do these values represent the boundary of the coordinate of every single object in entity? MAX ＆ MIN

**Comment by spheenik** [comment]
The theoretical boundary is min (X/Y) -16384/-16384 to max (X/Y)16383/16383. Why do you ask?

**Comment by CharlesLiuyx** [comment]
Thanks for your answer~ That is because I found in the clarity-analyzer, there is a little misalignment between the minimap and the objects(heroes, building, and etc.)

**Comment by spheenik** [comment]
Yes, the minimap image I use is very abstract, and I could have spent some more time to properly adjust ;-)

**Comment by CharlesLiuyx** [comment]
Yep! The m_cellX and m_cellY are between 0 - 256(I am not sure for this because I hardly found this value less than 70). (128,128) is center of the minimap. Am I right?

**Comment by spheenik** [comment]
I'm not sure if exactly, but approximately, yes.

**Comment by CharlesLiuyx** [comment]
I have checked it, the coordinate system is from  64 - 192. Thank you
