### ISSUE TITLE
How to get bans and picks from basic info? They are not returned.

### ISSUE THREAD

**Issue by ACmagic** [skadistats/clarity-examples#38]

**Comment by spheenik** [comment]
Hmm, it's a long time ago I last worked with basic info. If they are not there, then the replay most probably does not contain them. If you want me to check, please give me a match id.

**Comment by ACmagic** [comment]
Sorry for the misunderstanding. Basic info works fine for the public reply, but picks and bans are not returned for reply of private lobby.

**Comment by spheenik** [comment]
Then it's not provided for private lobbies.
