### ISSUE TITLE
Abilities info

### ISSUE THREAD

**Issue by uSide** [skadistats/clarity-examples#4]
I found old abilities info parsing [manual](https://github.com/skadistats/skadi/wiki/DT_DOTABaseAbility), but I don't know how parse this using clarity. Can someone help me?

**Comment by spheenik** [comment]
Here is a Gist

https://gist.github.com/spheenik/2271d2c9a340ee594806

that shows how to get the kills of the first player.
It will give you a guideline on what you have to do to get at your info.

If you need more help, np :)

**Comment by uSide** [comment]
Thank's!

**Comment by uSide** [comment]
Oh. I'm try to get data from DT_DOTABaseAbility, but nothing happens.
I read a lot of https://github.com/yasp-dota/yasp sources and find [code](https://github.com/yasp-dota/yasp/blob/master/utility.js#L128), where programm gets [ability upgrades from steam](https://wiki.teamfortress.com/wiki/WebAPI/GetMatchDetails).
Is there a way to get this information using clarity? Because I have many replays that I want to parse, but them not recorded by valve (replays from my dedicated servers) :cry:

**Comment by spheenik** [comment]
Well if you wanna have all existing abilities, you can do something like this:

https://gist.github.com/spheenik/caa02067dd12e25d7bd4

You will have to find out which ability belongs to which hero though.

**Comment by spheenik** [comment]
updated the gist to show you how to find the hero.

**Comment by uSide** [comment]
Im noob in Java. How fix the "cannot find symbol: class Iterator" ?

**Comment by spheenik** [comment]
import java.util.Iterator;

**Comment by uSide** [comment]
Predicate requires java 8?

**Comment by uSide** [comment]
However, I changed Predicate to 

```java
Iterator<Entity> iterw = match.getEntities().getAllByDtName("DT_DOTABaseAbility");
```
and seems it works. Thank u
