### ISSUE TITLE
Jump to tick at n-th effective minute mark

### ISSUE THREAD

**Issue by rudpes** [skadistats/clarity-examples#43]
Greetings.

For a project of mine, I'm trying to read player status (gold, last hits, items ...) at the 5th, 10th, 15th minute of play. Is there a way to do so ? it is possible to jump to the tick at the n-th minute mark ?

Thanks

**Comment by rudpes** [comment]
Sorry, found the answers. Apologies for the alert :)

**Comment by spheenik** [comment]
Hmm, I'd say this is not trivial, so if you have a nice answer, share it, please!  :-)

**Comment by rudpes** [comment]
Will do, I'm still learning

I used info here https://github.com/skadistats/clarity/issues/218 to map the current minute.

As for the information. I'm still trying to find how to map the inventory of items. 

For Gold/EXP per min, I assume I have to track EXP/Gold earned until that tick ?

**Comment by spheenik** [comment]
I'm not sure...
