### ISSUE TITLE
Hi!How can i get the position and basic information of heroes of each tick? 

### ISSUE THREAD

**Issue by PeaXCD** [skadistats/clarity-examples#44]
Position is represented by X,Y.Basic information includes damage,armor,attack speed etc.

**Comment by spheenik** [comment]
Regarding positoin: https://github.com/skadistats/clarity/issues/200#issuecomment-500193095

For looking at entity data, and finding your way around it, see [clarity-analyzer](https://github.com/spheenik/clarity-analyzer).
