### ISSUE TITLE
How do I know the meaning of num?

### ISSUE THREAD

**Issue by zycjiemozyc** [skadistats/clarity-examples#45]
Hello, your work is very helpful for me, but I still have some questions.
For example in gameevents there is 'event type = 21'
What does the number '21' mean?
Is there any file show the numbers' meaning?
Thanks！

**Comment by spheenik** [comment]
Content of GameEvents is defined by a GameEventDescriptor.
See `GameEvent.toString` to see how the event and it's descriptor can be used to get a human readable representation of it.

**Comment by zycjiemozyc** [comment]
您发来的邮件已收到，我会尽快回复~~
                                                          ——张乙川
