### ISSUE TITLE
Item and ability names

### ISSUE THREAD

**Issue by vbashiri** [skadistats/clarity-examples#46]
Hi there,
I want to get hero abilities and items, but some of them don't have proper name.
like -> "class: CDOTA_Item". I don't mind if it is name or unique id as long as it is unique between different replays, too. I couldn't find any corresponding id or something.

this is an item entity:
![dotaItem](https://user-images.githubusercontent.com/7634291/82652786-747f8200-9c33-11ea-996e-832566d025f2.png)

**Comment by spheenik** [comment]
[This should help.](https://github.com/skadistats/clarity/issues/126#issuecomment-271798384)

**Comment by vbashiri** [comment]
Thank you very much. m_pEntity.m_nameStringableIndex did the trick for me. I have another question tho. Is there any way to extract player role from the .dem file. I know the role search is not added to game very long ago but is there anyway I can get selected role by any player?

**Comment by spheenik** [comment]
I have no idea.

**Comment by vbashiri** [comment]
Thanks anyway. <3
