### ISSUE TITLE
Is there data for fights in the demo? The "show fight recap" button of dota 2 client

### ISSUE THREAD

**Issue by Markxy** [skadistats/clarity-examples#49]
I'm looking if there's any data embedded in the demo associated with fights.
I'm talking about these when watching a demo:
![image](https://user-images.githubusercontent.com/25804528/122565519-409da880-d04f-11eb-8fcc-d618574a875e.png)

It could be that the client is just simply collecting all the data by itself and the demo doesn't contain that info.
I also know that it could be doable based on kills, damage dealt, abilities used, etc - Opendota parses the demo and creates [it's own thing](https://github.com/odota/core/blob/461a5cb51cf3508e04edd6dd0b0498bc776f86b0/processors/processTeamfights.js) where they decide what is a teamfight and what's not.

But what I'm wondering is that is the data already there? And if so, how should I go about looking for it?
If I know the tick of the popup, could I dump all of the demo's info close to that tick somehow and see if that contains anything?

I went through clarity-examples but no output seemed to contain this.

Any pointers?

**Comment by spheenik** [comment]
I'm pretty confident the data is not there. The way of finding out definitively is to look at the list of all the different messages that can be found in the replay:

[EmbeddedPackets](https://github.com/skadistats/clarity-protobuf/blob/06462f2215628f5531f06de5ab5fdb6baf192ffb/src/main/java/skadistats/clarity/wire/s2/EmbeddedPackets.java)

The ones that are commented out are defined in the game, but have never been seen in a replay. It might be that the ones NOT commented are also NOT in the replay, but most of them are.

If you look at the file, there is no `teamfight`, `summary`, etc. in it. So you must use the same approch as the opendota guys.

Good luck!

**Comment by Markxy** [comment]
Thanks, @spheenik !

Yeah it looks like you're right, I went over them multiple times and didn't find anything significant.
Manual parsing it is.

Closing the question. Thanks again 🙂
