### ISSUE TITLE
Update Clarity Examples?

### ISSUE THREAD

**Issue by EdbertChan** [skadistats/clarity-examples#5]
Can you update the clarity examples?

For several examples (such as the info), they require 
import skadistats.clarity.wire....

However, package wire appears to have been removed in the latest build of Clarity.

**Comment by spheenik** [comment]
Hey man,

those imports are in a separate project (and jar):

https://github.com/skadistats/clarity-protobuf

It should be listed as a dependency in clarities pom.xml.

HTH,
Martin

**Comment by spheenik** [comment]
Hi,
everything all right now? If so, feel free to close this bug :)

**Comment by EdbertChan** [comment]
Yeah it seems like I accidentally screwed up my project setup. Sorry about that!

**Comment by spheenik** [comment]
No need to apologize :)
