### ISSUE TITLE
How to get all info contained in the replay as text output?

### ISSUE THREAD

**Issue by RuiLiFeng** [skadistats/clarity-examples#61]
I want to exactly recover all info in the replay .dem file. Is there any package can do this?

**Comment by spheenik** [comment]
There is so much "info" in the replay, that it's impossible to extract "everything as text".
You'll have to be more specific on what you want.

**Comment by RuiLiFeng** [comment]
Thank you for your reply, precisely, I want the below info
1. at each frame, the state of all heroes, units, buildings in the game
2. at each frame, what action each hero, unit, building take, like attack, move, buy
3. hero names, appearance, their skills and corresponding visual effects
4. at each frame what actions each player take to their heroes, units, or buildings

I want those info so that I can create something like the dota2 web replay viewer
https://chromewebstore.google.com/detail/dota-2-replay-viewer/bkkpkppjgjgfnjpfohcmclijikaeonjo?hl=id

Is that possible? Thank you so much for your reply!

**Comment by spheenik** [comment]
I think a very good starting point would be the parser OpenDota uses:
https://github.com/odota/parser

**Comment by spheenik** [comment]
To add to that, what you're trying to achieve is not a small feat.
Here is my implementation of a "replay viewer":
https://github.com/spheenik/clarity-analyzer

**Comment by RuiLiFeng** [comment]
Thank you for your kind help!

I still have a question about getting massive replays. How can I download replays using matchids? I need a replay_salt parameter but I cannot find it using the steamAPI GetMatchDetails.

**Comment by spheenik** [comment]
@noxville Hey Ben, the salt is on the API somewhere, right?

**Comment by Noxville** [comment]
You need to make a GC request to get the salt (k_EMsgGCMatchDetailsRequest -> k_EMsgGCMatchDetailsResponse).

This is heavily rate-limited (100 per account per day && 500 per IP per day).

**Comment by spheenik** [comment]
Thanks Ben! <3

**Comment by RuiLiFeng** [comment]
Thank you all so much!

**Comment by RuiLiFeng** [comment]
Thank you so much Maritin!

Martin Schrodt ***@***.***> 于2024年4月20日周六 17:01写道：
