### ISSUE TITLE
pls how to pring hero postion?

### ISSUE THREAD

**Issue by vodcms** [skadistats/clarity-examples#7]
pls how to pring hero postion?

**Comment by spheenik** [comment]
Here is some old code that can get you going: https://gist.github.com/spheenik/3766744d47c170f25cf5

**Comment by vodcms** [comment]
i run is error Entity is have't  m_vecOrigin  property pls help me

**Comment by spheenik** [comment]
It’s hard for me to understand what your problem is.
What’s your native language?

**Comment by spheenik** [comment]
Sounds like the entity does not have „m_vecOrigin“?
Then it probably is no hero entity?

**Comment by vodcms** [comment]
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import skadistats.clarity.model.Entity;
import skadistats.clarity.processor.runner.Context;
import skadistats.clarity.processor.runner.SimpleRunner;
import skadistats.clarity.processor.tempentities.OnTempEntity;
import skadistats.clarity.source.MappedFileSource;

public class Main {

    private final Logger log = LoggerFactory.getLogger("da");
  @OnTempEntity
    public void onTempEntity(Context ctx, Entity e) {
        Object v = e.getProperty("m_vecOrigin")
        System.out.println(v);
    }

    public void run(String[] args) throws Exception {
        long tStart = System.currentTimeMillis();
        new SimpleRunner(new MappedFileSource("/Users/guest/Downloads/1667995496_replay.dem")).runWith(this);
        long tMatch = System.currentTimeMillis() - tStart;
        log.info("total time taken: {}s", (tMatch) / 1000.0);
    }

    public static void main(String[] args) throws Exception {
        new Main().run(args);
    }

}

**Comment by spheenik** [comment]
TempEntites are not real Entities!
They are used for showing effects like blood, muzzle flash etc.
Take a look at the MatchEnd example on how to get a real entity.
There's also `@OnEntityCreated` and `@OnEntityChanged`, you can play around with that :)

**Comment by howardchung** [comment]
I didn't know there was an @OnEntityCreated!

Might be a little faster than trying to check for new wards every second :)

**Comment by spheenik** [comment]
Be careful, they might reuse an entity spot, and you'd only get one call.
But I could hack together an @OnEntityEnters for that case pretty quickly. 
If you want that for the 2.1 release, could you write a small request for it on the main project?

**Comment by vodcms** [comment]
3Q

**Comment by vodcms** [comment]
thank @spheenik

**Comment by spheenik** [comment]
Sure @vodcms, np :)
Btw: You can just do e.toString() on an entity to get a nice dump of all it's properties.

**Comment by vodcms** [comment]
hi @spheenik  .where have about replay explian docuemnt? i do not understand properties

**Comment by spheenik** [comment]
hehe, there simply is none...
But if you can read code, here is the parser of YASP, that uses clarity in a lot of ways:
https://github.com/yasp-dota/yasp/blob/master/parser/src/main/java/yasp/Main.java

**Comment by Chonchonts** [comment]
I try to process my replay with this function, but there are nothing printed, it's strange :'(. My parameters are good?
```java 
@OnEntityUpdated
    public void onEntityUpdated(Context ctx, Entity e,int[] a, int b) {
        System.out.println( b);
    }

**Comment by spheenik** [comment]
which version of clarity are you using?

**Comment by Chonchonts** [comment]
The last version, snapshot 2.1.

**Comment by spheenik** [comment]
Then it was because of me, since exactly that one event is disabled in 2.1 at the moment, since it's signature was going to change.
I just pushed a new snapshot that should have the event again. It's signature changed, however:
```
@OnEntityUpdated
public void onEntityUpdated(Context ctx, Entity e, FieldPath[] changedPaths, int numChangedPaths) {
  // the first numChangedPaths entries in fieldPaths show exactly what properties have changed.
  // do *not* keep a reference to changedPaths, since it's reused by clarity! 
}

**Comment by Chonchonts** [comment]
Thanks, it works like a charm !

**Comment by spheenik** [comment]
you're welcome!
