### ISSUE TITLE
Gold/XP Reasons?

### ISSUE THREAD

**Issue by bwarren2** [skadistats/clarity-examples#9]
The combatlog appears to support information about gold/xp sources.  Is there documentation somewhere on what these IDs mean?

**Comment by howardchung** [comment]
Doesn't look like there's an official source but based on some manual checking:
https://github.com/yasp-dota/yasp/blob/master/sources.json#L56

8 appears to be cheats but we don't have that one listed.

**Comment by bwarren2** [comment]
Thanks for the heads up Howard!

**Comment by howardchung** [comment]
If you can figure out what the other numbers are (seems to be 0-15, I'm missing a few), please share :)

**Comment by bwarren2** [comment]
Can do.  I might wiki my understanding of things at some point, and will
keep you posted.
